### ISSUE TITLE
Ignite website still distributes version 1.1.0

### ISSUE THREAD

**Issue by akrherz** [igniterealtime/openfire-httpFileUpload-plugin#1]
...Migrated from [Ignite Jira OF-1659](https://issues.igniterealtime.org/browse/OF-1659)...

Http file upload component has version 1.2.0 released. Current plugin for Openfire only has 1.1.3 included. Plugin should be updated.

**Comment by wrooot** [comment]
Version 1.1.1 has 1.2.1 version of the component
