### ISSUE TITLE
Cannot upload files with Padé or IM via httpupload

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/openfire-httpFileUpload-plugin#23]
Cannot upload file to OF via httpfileupload plugin version 1.13

Instance versions : OF 4.6.0 httpupload plugin :+1: Padé 1.3.0
![screenshot152](https://user-images.githubusercontent.com/29485972/106786370-c4ca3300-664e-11eb-967c-1ac14304246d.png)
I use httpupload on many configs without problems but on this specific server **the FDQN name is not equal to the top XMPP Domain.** 2 SRV records are added at the top DNS level.
Error mess in logs i have in logs

```
2021.02.03 13:44:34 INFO  [pool-2413-thread-3]: nl.goodbytes.xmpp.xep0363.Component - Entity 'claude@conecto.com.br/pade-undefined-v6.0.0-Chrome88Linux-113046287' obtained slot for 'pic10.jpg' (1235312 bytes). PUT-URL: https://chat.conecto.com.br:3443/httpfileupload/11a867ef-3343-41f1-8b5b-67d6b12756b7/pic10.jpg GET-URL: https://chat.conecto.com.br:3443/httpfileupload/11a867ef-3343-41f1-8b5b-67d6b12756b7/pic10.jpg
```

In err.log

```
2021.02.03 13:44:22 org.jivesoftware.openfire.websocket.XmppWebSocket - Error detected; session: WebSocketSession[websocket=JettyAnnotatedEventDriver[org.jivesoftware.openfire.websocket.XmppWebSocket@7b3250c2],behavior=SERVER,connection=WebSocketServerConnection@6f5a29d3::DecryptedEndPoint@e3a464c{l=/172.17.0.5:3443,r=/94.103.99.221:42504,CLOSED,fill=-,flush=F,to=54787/300000},remote=WebSocketRemoteEndpoint@70182e78[batching=true],incoming=JettyAnnotatedEventDriver[org.jivesoftware.openfire.websocket.XmppWebSocket@7b3250c2],outgoing=ExtensionStack[queueSize=0,extensions=[permessage-deflate],incoming=org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension,outgoing=org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension]]
```

Put & Get URL looks fine.

I have defined the following properties : 
![screenshot153](https://user-images.githubusercontent.com/29485972/106787304-d7913780-664f-11eb-92c4-6ef689ee2381.png)

I have many servers running with this but always with FDQN=Servername=Domain , this is the only difference

Any option to analyse what is going wrong ? 
No clue if it is a bug or if it is a question of config

Any help or hint will help

Thx in advance fot your  inputs

**Comment by guusdk** [comment]
Lets find out if this is a problem in the plugin, or in the client. Can you test this with any other client?

**Comment by ClaudeStabile** [comment]
Hi Guus,

Thanks for very prompt reply. I just have one config/client like this but we can test and if needed i collect all info. I can do tests as it is not working for now
Just tell me what you need to analyze

**Comment by guusdk** [comment]
Simply try another client instead of Pade. Conversations should work, or Converse/inVerse (which you can install as a plugin for Openfire), and see if you can use those to use HTTP File Upload.

**Comment by ClaudeStabile** [comment]
I use Xabber on my android on same server and same problem

**Comment by ClaudeStabile** [comment]
I have this problem only on this server. All other instances i run are with servername=domain name all working fine with version 1.13 +OF 4.6.0 that's the only difference

**Comment by ClaudeStabile** [comment]
Another difference is the SSL cert. I use letsencrypt on all my servers except this one, it is a Go-Daddy cert No clue if this could impact

**Comment by guusdk** [comment]
Does your certificate cover both the XMPP domain name as well as the
hostname of the server? That is probably needed for the HTTP GET request to
succeed.

Op wo 3 feb. 2021 19:07 schreef Claude Stabile <notifications@github.com>:

**Comment by ClaudeStabile** [comment]
That's a good hint, probably not top domain and xmpp server certs are probably differents let me check this out

**Comment by ClaudeStabile** [comment]
After checking, the cert SSL for top domain and hostname is the same one

**Comment by ClaudeStabile** [comment]
I simulate same behavior on another server if i try to accès another host, same message is observed. Probably cert related but...
@guusdk Let me know if you need more infos or do some tests.
Feel free to contact me directly if it helps
![screenshot155](https://user-images.githubusercontent.com/29485972/106807192-2c8d7780-6669-11eb-8dbf-48d9d36f594e.png)

**Comment by guusdk** [comment]
Running httpfileupload on a host that does not equal the domain name of the XMPP server does work: we're doing it on the ignite server that I used as an example below.

With regards to that CORS error: have you enabled CORS in the HTTP-Bind configuration of Openfire? 

![Screenshot from 2021-02-04 08-48-27](https://user-images.githubusercontent.com/4253898/106861329-e87c9000-66c5-11eb-928d-ae4f84f60a5c.png)

It's hard for me to diagnose this problem without having access to the system. I _think_ that the http file upload service is not available at https://chat.conecto.com.br:3443/httpfileupload/, as the 404 mentions 'servlet: default' rather than 'servlet: servlet' which you see for instance at https://xmpp.igniterealtime.org:7483/httpfileupload/

As I'm fairly confident that this is not an issue/bug in the code, I'm closing this Github tracker. Support-type questions are best handled in the Ignite community, at https://discourse.igniterealtime.org/

**Comment by ClaudeStabile** [comment]
@guusdk I will interract with you in the open_chat discussion.
I also confirm that with domain xmpp = server it was workiing but for customer reasons i needed to use this config. So a bit weird.

Thanks for relevant inputs & help

That's the settings i currently have here :
![screenshot160](https://user-images.githubusercontent.com/29485972/106870948-00f2a780-66d2-11eb-8204-a070264696fb.png)
