### ISSUE TITLE
where should I set plugin.httpfileupload.announcedWebProtocol?

### ISSUE THREAD

**Issue by jared201** [igniterealtime/openfire-httpFileUpload-plugin#25]
Hi,

I tried to do this in the openfire.xml file
```
<plugin>
    <httpfileupload>
      <announcedWebProtocol>http</announcedWebProtocol>
    </httpfileupload>
  </plugin>
```
not sure if this the right thing to do

**Comment by bertoldirenzo** [comment]
To configure the maximum allowable file size to be uploaded by clients, the property plugin.httpfileupload.maxFileSize can be set to a value in bytes. If not set, a default value is used. To disable the file size limitation, set this property to a value of -1.

**To change the HTTP server protocol from the default value of "https" to "http" for example, the property plugin.httpfileupload.announcedWebProtocol can be set to new value.**

To change the HTTP server hostname from the default value used by Openfire, the property plugin.httpfileupload.announcedWebHost can be set to new value.

To change the HTTP server port from the default value (7443) used by Openfire, the property plugin.httpfileupload.announcedWebPort can be set to new value.

To change the web context root as announced to clients from the default value (/httpfileupload) used by Openfire, the property plugin.httpfileupload.announcedWebContextRoot can be set to new value.

**Comment by guusdk** [comment]
You can set these properties in the Openfire admin console, as shown in this screenshot:

![image](https://user-images.githubusercontent.com/4253898/140410768-1b7062a2-7092-4d23-845a-4829c8bc9878.png)
