### ISSUE TITLE
How to configure HTTPS domain names

### ISSUE THREAD

**Issue by pzhu1015** [igniterealtime/openfire-httpFileUpload-plugin#27]
The online environment does not use IP. If you want to use the HTTPS domain name instead of IP and port, how to configure it? The generated file URL is incorrect
https://192.168.1.100:7443/httpfileupload/xxxxxxx.png =>https://domain.com:7443/httpfileupload/xxxxxxx.png, 
instead of  https://domain.com/httpfileupload/xxxxxxx.png

**Comment by guusdk** [comment]
Please do not use this issue tracker as a support desk tool. For that, you can use our community forum at https://discourse.igniterealtime.org

You can reconfigure the URLs that are announced by setting a couple of system properties. This is documented in the readme file of the plugin.
