### ISSUE TITLE
Fix Maven build

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/openfire-httpFileUpload-plugin#4]
To build plugins for Openfire 4.3.0 pom.xml should include repositories tags pointing to Archiva. If plugin has pages in Admin Console, web.xml should also be added.

For references:
https://github.com/igniterealtime/openfire-clientControl-plugin/pull/11

**Comment by wrooot** [comment]
Maybe already fixed @guusdk ?

**Comment by guusdk** [comment]
Yeah, this appears to already been fixed. I'm unsure in what release it was added.
