### ISSUE TITLE
Allow announced URLs to be HTTP instead of HTTPS

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/openfire-httpFileUpload-plugin#6]
The URLs that the plugin sends to peers (on which data can be posted or retrieved) currently is HTTPS-based, hard-coded.

It should be possible to configure HTTP (unsecured) URLs.

**Comment by wrooot** [comment]
Fixed in 1.1.1?

**Comment by guusdk** [comment]
Yes! This can now be controlled by using the `plugin.httpfileupload.announcedWebProtocol` property.

**Comment by itaims** [comment]
Hi,

From where we can set this property? I tried to find it in Server Manager -> System Properties. I searched plugin.httpfileupload.announcedWebProtocol but was not able to find it there. 

I am using 'Openfire 4.6.2, build b61bce3' and 'HTTP File Upload 1.1.3'.

Please help me to find this property.

Thanks,

**Comment by akrherz** [comment]
@itaims you can add the property on that page at the bottom, if it currently is not listed.

**Comment by gjaekel** [comment]
@itaims It's common in the project to have such features configurable just directly via the registry in the first sprint. If it have settled in practice, the second sprint is to add it to the suitable Admin UI page. This also should include some textual hints.

If you're be able to, you might send in a corresponding patch for.

**Comment by MahaskaVillage** [comment]
This post goes back a year. I've just had the server stop allowing file uploads and the closest I've seen is that it may be set to https. I've gone through the list of ports from server to modem. Is there an update to finding these settings so that I can verify it?
