### ISSUE TITLE
maven pom.xml file needs to be updated

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/openfire-httpFileUpload-plugin#7]
I have not got my head around the new maven configuration for plugins. I used a custom version of my own to build a jar file in order to test. Can someone help please

**Comment by GregDThomas** [comment]
Looking at it now ...

**Comment by GregDThomas** [comment]
*NOTE* `SlotManager.getInstance().setWebPath( "httpfileupload" );` is commented out in order for things to compile.

**Comment by deleolajide** [comment]
Thank you
